

CREATE TABLE IF NOT EXISTS books (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS authors (
  id INT PRIMARY KEY AUTO_INCREMENT,
  author VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS books_authors (
  id INT PRIMARY KEY AUTO_INCREMENT,
  book_id INT NOT NULL,
  author_id INT NOT NULL
);